<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="Spectre.Console" Version="0.56.0"/>
    </ItemGroup>

    <ItemGroup>
        <ProjectReference Include="..\UnityAssetsPatcher.Application\UnityAssetsPatcher.Application.csproj"/>
        <ProjectReference Include="..\UnityAssetsPatcher.Core\UnityAssetsPatcher.Core.csproj"/>
    </ItemGroup>

    <ItemGroup>
        <EmbeddedResource Update="Localization\LocalizedStrings.resx">
            <Generator>ResXFileCodeGenerator</Generator>
            <LastGenOutput>LocalizedStrings.Designer.cs</LastGenOutput>
        </EmbeddedResource>
    </ItemGroup>

    <ItemGroup>
        <Compile Update="Localization\LocalizedStrings.Designer.cs">
            <DesignTime>True</DesignTime>
            <AutoGen>True</AutoGen>
            <DependentUpon>LocalizedStrings.resx</DependentUpon>
        </Compile>
    </ItemGroup>

</Project>
