<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <OutputType>Exe</OutputType>
        <TargetFramework>net10.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
        <PublishAot>true</PublishAot>
    </PropertyGroup>

    <ItemGroup>
        <EmbeddedResource Include="Assets\resources.tpk" LogicalName="resources.tpk"/>
    </ItemGroup>

    <ItemGroup>
        <PackageReference Include="Microsoft.Extensions.DependencyInjection" Version="11.0.0-preview.6.26359.118"/>
    </ItemGroup>

    <ItemGroup>
        <ProjectReference Include="..\UnityAssetsPatcher.CLI\UnityAssetsPatcher.CLI.csproj"/>
        <ProjectReference Include="..\UnityAssetsPatcher.Application\UnityAssetsPatcher.Application.csproj"/>
        <ProjectReference Include="..\UnityAssetsPatcher.AssetsTools\UnityAssetsPatcher.AssetsTools.csproj"/>
        <ProjectReference Include="..\UnityAssetsPatcher.TUI\UnityAssetsPatcher.TUI.csproj"/>
    </ItemGroup>

</Project>
