//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UnityAssetsPatcher.TUI.Localization {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class LocalizedStrings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal LocalizedStrings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("UnityAssetsPatcher.TUI.Localization.LocalizedStrings", typeof(LocalizedStrings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Analyzing mod....
        /// </summary>
        internal static string InstallPage_AnalyzingMod {
            get {
                return ResourceManager.GetString("InstallPage_AnalyzingMod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Apply these changes?.
        /// </summary>
        internal static string InstallPage_ApplyTheseChangesPrompt {
            get {
                return ResourceManager.GetString("InstallPage_ApplyTheseChangesPrompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} changing, {1} skipped.
        /// </summary>
        internal static string InstallPage_ChangingOperationCountsFormat {
            get {
                return ResourceManager.GetString("InstallPage_ChangingOperationCountsFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Analyze the mod first, then confirm before writing files.
        /// </summary>
        internal static string InstallPage_Description {
            get {
                return ResourceManager.GetString("InstallPage_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Game directory.
        /// </summary>
        internal static string InstallPage_GameDirectoryPrompt {
            get {
                return ResourceManager.GetString("InstallPage_GameDirectoryPrompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Install canceled..
        /// </summary>
        internal static string InstallPage_InstallCanceled {
            get {
                return ResourceManager.GetString("InstallPage_InstallCanceled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mod zip path.
        /// </summary>
        internal static string InstallPage_ModZipPathPrompt {
            get {
                return ResourceManager.GetString("InstallPage_ModZipPathPrompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PREVIEW.
        /// </summary>
        internal static string InstallPreview_DryRunStatus {
            get {
                return ResourceManager.GetString("InstallPreview_DryRunStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to InstallPreview_Targets.
        /// </summary>
        internal static string InstallPreview_Targets {
            get {
                return ResourceManager.GetString("InstallPreview_Targets", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to InstallResult_Backup.
        /// </summary>
        internal static string InstallResult_Backup {
            get {
                return ResourceManager.GetString("InstallResult_Backup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copied files.
        /// </summary>
        internal static string InstallResult_CopiedFiles {
            get {
                return ResourceManager.GetString("InstallResult_CopiedFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to INSTALLED.
        /// </summary>
        internal static string InstallResult_InstalledStatus {
            get {
                return ResourceManager.GetString("InstallResult_InstalledStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Patched files.
        /// </summary>
        internal static string InstallResult_PatchedFiles {
            get {
                return ResourceManager.GetString("InstallResult_PatchedFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Press any key to return to the main menu..
        /// </summary>
        internal static string Layout_ReturnToMainMenuPrompt {
            get {
                return ResourceManager.GetString("Layout_ReturnToMainMenuPrompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shortcuts: ↑/↓ to choose | Esc to cancel | Ctrl + C to exit.
        /// </summary>
        internal static string Layout_ShortcutHint {
            get {
                return ResourceManager.GetString("Layout_ShortcutHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Preview mod changes, then install with one click.
        /// </summary>
        internal static string MainMenu_InstallMod_Description {
            get {
                return ResourceManager.GetString("MainMenu_InstallMod_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Install Mod.
        /// </summary>
        internal static string MainMenu_InstallMod_Title {
            get {
                return ResourceManager.GetString("MainMenu_InstallMod_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Customize your experience..
        /// </summary>
        internal static string MainMenu_Settings_Description {
            get {
                return ResourceManager.GetString("MainMenu_Settings_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        internal static string MainMenu_Settings_Title {
            get {
                return ResourceManager.GetString("MainMenu_Settings_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Main menu.
        /// </summary>
        internal static string MainMenu_Title {
            get {
                return ResourceManager.GetString("MainMenu_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to y/N.
        /// </summary>
        internal static string Prompt_ConfirmationChoiceHint {
            get {
                return ResourceManager.GetString("Prompt_ConfirmationChoiceHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Directory not found: {0}.
        /// </summary>
        internal static string Prompt_DirectoryNotFoundFormat {
            get {
                return ResourceManager.GetString("Prompt_DirectoryNotFoundFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File not found: {0}.
        /// </summary>
        internal static string Prompt_FileNotFoundFormat {
            get {
                return ResourceManager.GetString("Prompt_FileNotFoundFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} must be greater than 0..
        /// </summary>
        internal static string Prompt_LabelMustBeGreaterThanZeroFormat {
            get {
                return ResourceManager.GetString("Prompt_LabelMustBeGreaterThanZeroFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} must be an integer..
        /// </summary>
        internal static string Prompt_LabelMustBeIntegerFormat {
            get {
                return ResourceManager.GetString("Prompt_LabelMustBeIntegerFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} is required..
        /// </summary>
        internal static string Prompt_LabelRequiredFormat {
            get {
                return ResourceManager.GetString("Prompt_LabelRequiredFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose y or n..
        /// </summary>
        internal static string Prompt_YesNoChoiceError {
            get {
                return ResourceManager.GetString("Prompt_YesNoChoiceError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Initial selected index must reference an available option..
        /// </summary>
        internal static string SelectionPrompt_InitialSelectedIndexOutOfRange {
            get {
                return ResourceManager.GetString("SelectionPrompt_InitialSelectedIndexOutOfRange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Option count must be greater than 0..
        /// </summary>
        internal static string SelectionPrompt_OptionCountOutOfRange {
            get {
                return ResourceManager.GetString("SelectionPrompt_OptionCountOutOfRange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Configure output detail..
        /// </summary>
        internal static string SettingsPage_ConfigureOutputDetailsDescription {
            get {
                return ResourceManager.GetString("SettingsPage_ConfigureOutputDetailsDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shortcuts: ↑/↓ to choose | Space to toggle | Esc to cancel | Ctrl + C to exit.
        /// </summary>
        internal static string SettingsPage_ShortcutHint {
            get {
                return ResourceManager.GetString("SettingsPage_ShortcutHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show detailed install preview logs and per-stage install timings..
        /// </summary>
        internal static string SettingsPage_VerboseLoggingDescription {
            get {
                return ResourceManager.GetString("SettingsPage_VerboseLoggingDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Verbose output.
        /// </summary>
        internal static string SettingsPage_VerboseLoggingName {
            get {
                return ResourceManager.GetString("SettingsPage_VerboseLoggingName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Assets.
        /// </summary>
        internal static string Summary_Assets {
            get {
                return ResourceManager.GetString("Summary_Assets", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Author.
        /// </summary>
        internal static string Summary_Author {
            get {
                return ResourceManager.GetString("Summary_Author", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to asset(s).
        /// </summary>
        internal static string Summary_AssetUnit {
            get {
                return ResourceManager.GetString("Summary_AssetUnit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Summary_Elapsed.
        /// </summary>
        internal static string Summary_Elapsed {
            get {
                return ResourceManager.GetString("Summary_Elapsed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mod.
        /// </summary>
        internal static string Summary_Mod {
            get {
                return ResourceManager.GetString("Summary_Mod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Operations.
        /// </summary>
        internal static string Summary_Operations {
            get {
                return ResourceManager.GetString("Summary_Operations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to operation(s).
        /// </summary>
        internal static string Summary_OperationUnit {
            get {
                return ResourceManager.GetString("Summary_OperationUnit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Summary_Version.
        /// </summary>
        internal static string Summary_Version {
            get {
                return ResourceManager.GetString("Summary_Version", resourceCulture);
            }
        }
    }
}
